### ISSUE TITLE
The basic function of the site works!

### ISSUE THREAD

**Issue by mikeducey** [omahacodeschool/block-16-notifier#1]
So, I believe the site works as intended, though I can think of a few things that could be programmed into the logic just as failsafes in case a few things go wrong.  But for now, I think I can say that the master copy can be worked with for now (on the front end).  

How the site works:

A visitor comes and enters their phone number.  A site admin then visits the /facebook link, which will go and check the facebook api to see if there are new specials.  If there is a new special (like a morning special, and not the random other posts from the day), it will be saved to the database.

Then, the admin will visit /blast, which will send a blast with the specials info to the subscribers.  It also updates the database record, changing it so that the info recorded will not be sent again, so users won't get duplicate information!

It should be deploy-able, at least once the front end is in place.  But I can think of a few things that will could be improved, small fixes, that I'll visit in the coming days.

**Comment by sumeetjain** [comment]
- [x] Entering `fwewefwe` as the phone number submitted the form and returned "Your email has been added to the Block 16 Notifier list!". Look into ActiveRecord validations.
- [x] Password-protect the pages that trigger calls to 3rd party services. Keep it simple, for now: Use this [basic example](http://api.rubyonrails.org/classes/ActionController/HttpAuthentication/Basic.html), but set the username and password in **.env.local** so people can't get the passwords simply by viewing this repo.
- [ ] [Design Implementation](https://github.com/omahacodeschool/block-16-notifier/issues/2)
