### ISSUE TITLE
Cleaner truncation of text

### ISSUE THREAD

**Issue by halfghaninne** [omahacodeschool/block-16-notifier#5]
Cut of text from Facebook after a word, rather than in the middle of a word.

**Comment by mikeducey** [comment]
This has been completed, and there is documentation in the method to explain my code and thought process.  It should be an easy enough to explain method, it just takes the characters after the automatically added part (a small limit of the first part of the facebook post text), checks to see if it is a white space character, and if not, takes the first section of letters (the rest of the word that was cut off from the automatically added part) and attaches it back onto the automatically included text.  I just realized how hard it is to explain that!
